### ISSUE TITLE
[1.7.10] LomLib - excessive pause/unable to check for update

### ISSUE THREAD

**Issue by spannerman79** [Lomeli12/LomLib#4]
Currently for whatever reason whenever my server loads up LomLib it more or less "hangs" for a good minute or two.

**Comment by Lomeli12** [comment]
1.7 or 1.8?

**Comment by spannerman79** [comment]
Sorry my bad [LomLib-1.7.10-3.2.0-universal.jar](http://minecraft.curseforge.com/projects/lomlib/files/2240927)

**Comment by Lomeli12** [comment]
I'll probably just disable the updater for the 1.7.10 version since I'm not actively developing it anyway, it'll be on CurseForge in a bit. I do need to remember to put the updater on a separate thread to prevent this on the 1.8 version.

**Comment by spannerman79** [comment]
:+1: Thanks.

Its not an major issue, only some of my friends have noticed slower server startup times when i have scheduled restarts.

And as none of them have any idea how to setup and run a Forge server ... yeah I think you get the direction I'm heading haha.
